services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    restart: unless-stopped
    image: felipethales/monitoring-demo-app:latest
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./app/logs:/app/logs
    #healthcheck:
      #test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      #interval: 10s
      #timeout: 5s
      #retries: 3
      #start_period: 10s
    #Dando error, resolver nas próximas versões do docker-compose  

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      prometheus:
        condition: service_started

volumes:
  grafana-storage: